version: 2
builds:
    main: .
    binary: corn
    # Default: [ 'darwin', 'linux', 'windows' ].
    goos:
      - darwin
      - linux
    # GOARCH to build for.
    # For more info refer to: https://pkg.go.dev/cmd/go#hdr-Environment_variables
    #
    # Default: [ '386', 'amd64', 'arm64' ].
    goarch:
      - amd64
      - arm
      - arm64
