disableNotifications: false
defaultNotifier: base
jobs:
  testJob:
    schedules:
      - "@TEST_TIME"
    command: kjflkadsjflkd kjkjdkfj
    onlyLogOnFail: false
    failStrategy:
      retry:
        maxRetries: 4
notifiers:
  base:
    telegram:
      - token: "TELEGRAM_TOKEN"
        receivers:
          - 123456
